// First, Whatever The let Variable's Value Is, We Can Change It Later On,
// And This Is A Perfect Example, Since The age Of A Person Can Change:
let age = 15;
age = 16
// The const Variable's Value Can't Be Changed, And Is Called An Immutable Value,
// Just Like The birthYear Of A Person Can't Change:
const birthYear = 2009; // ✔️
// birthYear = 2010; ✖️
// Also const Requires A Value, You Can't Make A Value And Leave It Undefined

//There Is Also var:
var job = "Programmer";
job = "Professor";
// You Can Also Change The Value Of The Variable, And By Now You Might Think
// That var And let Are Pretty Similar, But They Are Actually Not, And Even If Both Work,
// var Is An Old Version Of let, So Its Better To Use let Than var, let Also Does
// Alot Of Other Stuff var Does'nt, So Its Good Practice To Use let Instead Of var

// This Also Works, But Using This Is A Terrible Idea And I
// Advise You To Never Use This (Maybe Sometimes):
firstName = 'James';
console.log(firstName);









