let js = 'amazing';
// 40 + 8 + 23 - 10; ✖️
console.log(40 + 8 + 23 - 10); // ✔️

console.log("Unkox");
console.log(16);

let firstName = "Moose";
let first = "Bison";
let firstNamePerson
console.log(firstName);

// let Thing = "Haybale" ✖️
let thing = "HayBale" // ✔️

// Also Variable Names CAN NOT Start With A Number,
// And Only "_" or "$" Special Characters Can Be Used
// Also, Even Though it Works And Maybe Looks Good
// Try Not To Type The First Letter Of A Word To A Capital Letter
// Even If It Works, Because They Are Used For Other Things
// Like object-oriented-programming,

// We Also Try To Be More Descriptive,
// As It Helps Us Know Which Variable To Use At A Specific Place
// Take The Following For Example:

// let job1 = "Programmer";
// let job2 = "Professor"; // ✖️

// The Above One Just Tells Us About 2 Jobs, Not That It Was His First Or 2nd Job,
// While The One Below Tells Us The Exact Info We Need, This Makes The Code More Understandable

let myFirstJob = "Programmer";
let myCurrentJob = "Professor"; // ✔️

console.log(myFirstJob);



























